name: qyre_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.1

flutter_native_splash:
  image: assets/images/logo.png
  color: "000000"
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  image_path: assets/images/logo.png
  ios: true
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Matter
      fonts:
        - asset: assets/fonts/Matter-Bold.otf
        - asset: assets/fonts/matter-light.otf
        - asset: assets/fonts/matter-medium.otf
        - asset: assets/fonts/Matter-Regular.eot
        - asset: assets/fonts/Matter-SemiBold.eot


